# Generated by Django 4.1.1 on 2024-06-26 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.IntegerField(default=0, null=True)),
                ('delivery_address', models.CharField(max_length=100, null=True)),
                ('user_address', models.CharField(max_length=100, null=True)),
                ('date_of_sale', models.DateField(null=True)),
                ('status', models.CharField(max_length=42, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=42, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=42, null=True)),
                ('last_name', models.CharField(max_length=42, null=True)),
                ('email', models.CharField(max_length=128, null=True, unique=True)),
                ('password', models.CharField(max_length=80, null=True)),
                ('address', models.CharField(max_length=80, null=True)),
                ('phone_number', models.IntegerField(default=0, null=True, unique=True)),
                ('city', models.CharField(max_length=42, null=True)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.role')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'email', 'phone_number', 'city'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('thumbnail', models.CharField(max_length=500, null=True)),
                ('price', models.IntegerField(default=0, null=True)),
                ('product_type', models.CharField(max_length=42, null=True)),
                ('stock', models.IntegerField(default=0, null=True)),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.manufacturer')),
            ],
            options={
                'ordering': ['title', 'stock', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField(default=0, null=True)),
                ('Order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.order')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.IntegerField(default=0, null=True)),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('Order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.order')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.user'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42, null=True)),
                ('Product', models.ManyToManyField(related_name='category', to='viewer.product')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('Product', models.ManyToManyField(related_name='cart', to='viewer.product')),
            ],
        ),
    ]
